name: B12 application

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run submission script
        env:
          ACTION_RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          sed -i "s|YOUR_RUN_ID|${{ github.run_id }}|g" submit.py
          sed -i "s|YOUR_USERNAME/YOUR_REPO|${{ github.repository }}|g" submit.py
          python submit.py
